# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 137826b21fe16cebd443744b229f5349224ec196e9e92feb175a77e6ece42a0e2d1f102bc66aca28428cc7c151b02dd87b2d2a0dd61143526738319332a91528

test:
  secret_key_base: 4d66d214c9bd505e0750c97eb96dbe5cd2099d14dae8997e9bffeb2d47a52af2572ce329b050ba457c60492d2c79b7667009e1e55f4b09db89a373086997c162

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
